version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=cs261
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    build:
      context: ./
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local