name: CI

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Remove .env
        run: php -r "file_exists('.env') || unlink('.env');"

      - name: Directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests
        env:
          DB_CONNECTION: pgsql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_TEST_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_TEST_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_TEST_PASSWORD }}
          CS261_TEST_RECAPTCHA_OVERRIDE: ${{ secrets.CS261_TEST_RECAPTCHA_OVERRIDE }}

        run: vendor/bin/phpunit\

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Lint code
        run: composer cs:check

  deploy:
    name: Deploy
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker
        run: |
          gcloud auth configure-docker

      - name: Build container
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/cs261-api:latest .

      - name: Push container
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/cs261-api:latest

      - name: Deploy container
        run: |
          gcloud run deploy cs261-api \
          --region europe-west2 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/cs261-api \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}

  migrate:
    name: Migrate
    needs: [deploy]
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Migrate database
        env:
          DB_CONNECTION: pgsql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: php artisan migrate --force

